language: csharp
sudo: false
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - SIGNALR_TESTS_VERBOSE: 1
    - TRAVIS_NODE_VERSION: 6.9.1
mono: none
python:
  - "2.7"
os:
  - linux
  - osx
osx_image: xcode8.2
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
    - /^rel\/.*/
before_install:
  - if test "$TRAVIS_OS_NAME" == "linux"; then nvm install $TRAVIS_NODE_VERSION; fi
install:
  - pip install autobahntestsuite "six>=1.9.0"
script:
  - ./build.sh
