language: csharp
sudo: required
dist: trusty
services:
- docker
env:
  global:
  - SIGNALR_TESTS_VERBOSE: 1
  - TRAVIS_NODE_VERSION: 8.9.3
mono: none
os:
- linux
- osx
osx_image: xcode8.2
addons:
  chrome: stable
  apt:
    packages:
    - libunwind8
branches:
  only:
  - dev
  - /^release\/.*$/
  - /^(.*\/)?ci-.*$/
before_install:
- nvm install $TRAVIS_NODE_VERSION
- if test "$TRAVIS_OS_NAME" == "linux"; then docker pull redis; fi
script:
- npx which google-chrome
- npx which google-chrome-stable
- npx which chromium
- npx which chromium-browser
- ./build.sh --ci
