language: csharp
sudo: required
dist: trusty
services:
  - docker
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - SIGNALR_TESTS_VERBOSE: 1
    - TRAVIS_NODE_VERSION: 8.0.0
mono: none
os:
  - linux
  - osx
osx_image: xcode8.2
addons:
  apt:
    packages:
      - libunwind8
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
    - /^rel\/.*/
before_install:
  - if test "$TRAVIS_OS_NAME" == "linux"; then nvm install $TRAVIS_NODE_VERSION; fi
script:
  - ./build.sh
