image: Visual Studio 2015
init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
build_script:
  - ps: .\build.ps1
install:
  - ps: Install-Product node 6
clone_depth: 1
test: off
deploy: off
os: Visual Studio 2017
