/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class HubConnectionTest {
    @Test public void testSomeLibraryMethod() {
        HubConnection classUnderTest = new HubConnection();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
