trigger:
- master
- release/*

resources:
  repositories:
  - repository: buildtools
    type: git
    name: aspnet-BuildTools
    ref: refs/heads/release/2.2

phases:
- template: .vsts-pipelines/templates/project-ci.yml@buildtools
  parameters:
    beforeBuild:
    - task: NodeTool@0
      displayName: Use Node 10.x
      inputs:
        versionSpec: '10.x'
