trigger:
- master
- release/*

# See https://github.com/aspnet/BuildTools
resources:
  repositories:
  - repository: buildtools
    type: github
    endpoint: DotNet-Bot GitHub Connection
    name: aspnet/BuildTools
    ref: refs/heads/release/2.2

jobs:
- template: .azure/templates/project-ci.yml@buildtools
  parameters:
    variables:
      ASPNETCORE_SIGNALR_TEST_ALL_BROWSERS: true
    beforeBuild:
    - task: NodeTool@0
      displayName: Use Node 8.x
      inputs:
        versionSpec: 8.x
