trigger:
- master
- release/*

# See https://github.com/aspnet/BuildTools
resources:
  repositories:
  - repository: buildtools
    type: github
    endpoint: DotNet-Bot GitHub Connection
    name: aspnet/BuildTools
    ref: refs/heads/release/2.2

phases:
- template: .azure/templates/jobs/default-build.yml@buildtools
  parameters:
    agentOs: Windows
    beforeBuild:
    - task: NodeTool@0
      displayName: Use Node 8.x
      inputs:
        versionSpec: 8.x

- template: .azure/templates/jobs/default-build.yml@buildtools
  parameters:
    agentOs: macOS
    beforeBuild:
    - task: NodeTool@0
      displayName: Use Node 8.x
      inputs:
        versionSpec: 8.x

- template: .azure/templates/jobs/default-build.yml@buildtools
  parameters:
    agentOs: Linux
    beforeBuild:
    - task: NodeTool@0
      displayName: Use Node 8.x
      inputs:
        versionSpec: 8.x
